---
  - hosts: all
    tasks:
      - name: install packages
        apt: name={{ item }} state=present
        become: true
        with_items:
          - curl
          - wget
          - vim
          - unzip

      - name: install xubuntu desktop
        apt: name=xubuntu-desktop state=present
        ignore_errors: yes
        become: true
